version: '3'


services:
  nuxt:
    build:
      context: .
      dockerfile: ./compose/local/nuxt/Dockerfile
    image: vuejs_django_course_local_nuxt
    container_name: vuejs_django_course_local_nuxt_lone
    user: ${DOCKER_USER}
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - ./portfolio:/app
