version: '3'


services:
  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: vuejs_django_course_local_node
    container_name: vuejs_django_course_local_node
    volumes:
      - ./vuejs-frontend/gs-02-first-app-with-just-js:/app:z
