# Generated by Django 4.2.9 on 2024-02-14 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurrentPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the payment. For example: Life insurance, Cellphone, etc.", max_length=100
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, help_text="Amount of the payment", max_digits=10)),
                ("description", models.TextField(blank=True, help_text="Description of the payment", null=True)),
                ("date_due", models.DateField(help_text="Date when the payment is due")),
                ("is_active", models.BooleanField(default=True, help_text="Is the payment active?")),
                ("is_amount_fixed", models.BooleanField(default=True, help_text="Is the amount fixed?")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("date", models.DateTimeField(help_text="Date of the payment")),
                ("amount", models.DecimalField(decimal_places=2, help_text="Amount of the payment", max_digits=10)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modified_%(class)s",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recurrent_payment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="payments.recurrentpayment"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
