# Generated by Django 4.2.9 on 2024-02-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ("date",)},
        ),
        migrations.AddField(
            model_name="payment",
            name="comments",
            field=models.TextField(blank=True, help_text="Comments of the payment", null=True),
        ),
    ]
